# Generated by Django 4.2.4 on 2023-08-21 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('feature_image', models.ImageField(upload_to='blog/', verbose_name='Feature Image')),
                ('status', models.CharField(choices=[('public', 'Public'), ('draft', 'Draft')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
