# Generated by Django 4.2.4 on 2023-08-23 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testexam',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='tests/'),
        ),
    ]
