# Generated by Django 4.2.4 on 2023-08-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_testexam_testname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testexam',
            name='testname',
            field=models.CharField(max_length=100),
        ),
    ]
