# Generated by Django 4.2.4 on 2023-08-23 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_alter_testexam_testname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexam',
            old_name='testname',
            new_name='test_name',
        ),
    ]
