# Generated by Django 4.2.4 on 2023-08-23 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_rename_testname_testexam_test_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testexam',
            options={'ordering': ['id']},
        ),
    ]
