# Generated by Django 4.2.4 on 2023-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_testexam_require_points'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexam',
            old_name='require_points',
            new_name='purchased_points',
        ),
        migrations.AddField(
            model_name='testexam',
            name='passmarks',
            field=models.PositiveIntegerField(default=40),
        ),
    ]
