# Generated by Django 4.2.4 on 2023-08-24 03:59

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_require_points_testexam_purchased_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=tinymce.models.HTMLField(help_text='What is the value of PI ?', verbose_name='Question'),
        ),
    ]
