# Generated by Django 4.2.4 on 2023-08-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_alter_testquestion_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestion',
            name='question',
            field=models.CharField(help_text='What is the value of PI ?', verbose_name='Question'),
        ),
    ]
